language: java
sudo: required
jdk:
- openjdk14
addons:
  sonarcloud:
    organization: "vatbub-github"
cache:
  directories:
  - $HOME/.m2
before_install:
  - openssl aes-256-cbc -K $encrypted_b3fe6148db0d_key -iv $encrypted_b3fe6148db0d_iv -in github_deploy_key.enc -out github_deploy_key -d
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar --settings travisMavenSettings.xml
after_success:
  - source ./travisAfterSuccess.sh
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
