language: java
sudo: required
jdk:
- openjdk14
cache:
  directories:
  - $HOME/.m2
before_install:
  - openssl aes-256-cbc -K $encrypted_b3fe6148db0d_key -iv $encrypted_b3fe6148db0d_iv -in github_deploy_key.enc -out github_deploy_key -d
install:
  - wget https://s3.eu-central-1.amazonaws.com/vatbubjdk/OpenJDK21U-jdk_x64_linux_hotspot_21.0.8_9.tar.gz -nv
  - tar -xf OpenJDK21U-jdk_x64_linux_hotspot_21.0.8_9.tar.gz
  - export JAVA_HOME=/home/travis/build/vatbub/commandlineUserPromptProcessor/jdk-21.0.8+9
script:
- mvn verify --settings travisMavenSettings.xml
after_success:
  - source ./travisAfterSuccess.sh
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
